import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create schema auth; create table auth.users(id uuid primary key);create role anon;create role authenticated;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/202610060001_initial.sql', import.meta.url),'utf8'));
await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
const c=(await db.query(`insert into public.challenges(name) values('A') returning id`)).rows[0].id;
await db.query(`insert into public.submissions(challenge_id,version,score) values($1,'v1',0)`,[c]);
await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
assert.equal((await db.query('select * from public.challenges')).rows.length,0);assert.equal((await db.query('select * from public.submissions')).rows.length,0);
await assert.rejects(()=>db.query(`insert into public.submissions(challenge_id,version,score) values($1,'bad',1)`,[c]));
await db.exec(`set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
const payload={challenges:[{id:'legacy-challenge',name:'Imported',tags:['tabular'],direction:'desc',baseline:0,estEarn:22,publicRank:5,privateRank:2,submissions:[{id:'legacy-sub',version:'v2',score:.9,status:'Approved'}]}]};
await db.query('select public.import_legacy_tracker($1::jsonb)',[JSON.stringify(payload)]);await db.query('select public.import_legacy_tracker($1::jsonb)',[JSON.stringify(payload)]);
assert.equal((await db.query('select * from public.challenges')).rows.length,2);assert.equal((await db.query('select * from public.submissions')).rows.length,2);
const bad={challenges:[{id:'rollback1',name:'Should rollback',tags:[],submissions:[]},{id:'rollback2',name:'Invalid rank',tags:[],privateRank:-1,submissions:[]}]};await assert.rejects(()=>db.query('select public.import_legacy_tracker($1::jsonb)',[JSON.stringify(bad)]));assert.equal((await db.query(`select * from public.challenges where name='Should rollback'`)).rows.length,0);
await db.query('delete from public.challenges where id=$1',[c]);assert.equal((await db.query('select * from public.submissions')).rows.length,1);
console.log('PASS SQL migration, owner RLS isolation, cross-owner insert rejection, idempotent import, atomic rollback, cascade delete');await db.close();
