import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const one='11111111-1111-4111-8111-111111111111',two='22222222-2222-4222-8222-222222222222';
await db.exec(`create schema auth;create table auth.users(id uuid primary key);create role anon;create role authenticated;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;insert into auth.users values('${one}'),('${two}');`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/202610060001_initial.sql',import.meta.url),'utf8'));
await db.query(`insert into public.challenges(user_id,name,baseline,direction,private_rank) values ($1,'Higher',.3,'desc',NULL),($1,'Lower',.1,'asc',NULL),($1,'Failed',NULL,'desc',NULL),($1,'Empty',NULL,'desc',NULL),($1,'Top',NULL,'desc',2)`,[one]);
for(const [name,scores] of [['Higher',[[0,'Pending review'],[.8,'Rejected']]],['Lower',[[0,'Pending review'],[.8,'Rejected']]],['Failed',[[.4,'Rejected']]]]){
 const cid=(await db.query('select id from public.challenges where name=$1',[name])).rows[0].id;
 for(const [score,status] of scores)await db.query('insert into public.submissions(challenge_id,version,score,status) values($1,$2,$3,$4)',[cid,String(score),score,status]);
}
await db.exec(fs.readFileSync(new URL('../supabase/challenge_results.sql',import.meta.url),'utf8'));
const converted=(await db.query('select * from public.challenges order by name')).rows;
assert.equal(converted.find(c=>c.name==='Higher').public_score,.8);
assert.equal(converted.find(c=>c.name==='Lower').public_score,0);
assert.equal(converted.find(c=>c.name==='Higher').public_baseline,.3);
assert.equal(converted.find(c=>c.name==='Higher').status_override,'Pass');
assert.equal(converted.find(c=>c.name==='Failed').status_override,'Fail');
assert.equal(converted.find(c=>c.name==='Empty').status_override,null);
assert.equal(converted.find(c=>c.name==='Top').status_override,'Top leaderboard');
assert.ok(converted.every(c=>c.private_score===null&&c.private_baseline===null&&c.difficulty===null));
assert.equal((await db.query("select to_regclass('public.submissions') as x")).rows[0].x,null);
assert.equal((await db.query("select to_regprocedure('public.import_legacy_tracker(jsonb)') as x")).rows[0].x,null);
await db.exec(`set role authenticated;set request.jwt.claim.sub='${one}';`);
const payload={challenges:[{id:'backup-1',name:'Imported',type:'NLP',tags:['language'],direction:'asc',public_baseline:0,private_baseline:.2,public_score:0,private_score:.1,difficulty:'Hard',est_earn:0,actual_earn:20,public_rank:10,private_rank:5,status_override:'Pass',created_at:'2026-10-01T14:30:00+07:00'}]};
await db.query('select public.import_tracker($1::jsonb)',[JSON.stringify(payload)]);await db.query('select public.import_tracker($1::jsonb)',[JSON.stringify(payload)]);
const imported=(await db.query("select * from public.challenges where name='Imported'")).rows[0];
assert.equal(imported.public_score,0);assert.equal(imported.private_score,.1);assert.equal(imported.difficulty,'Hard');
assert.equal(new Date(imported.created_at).toISOString(),'2026-10-01T07:30:00.000Z');
assert.equal((await db.query('select count(*)::int as n from public.challenges')).rows[0].n,6);
await db.query('update public.challenges set private_score=$1,status_override=$2 where id=$3',[.12,'Fail',imported.id]);
assert.equal((await db.query('select private_score,status_override from public.challenges where id=$1',[imported.id])).rows[0].private_score,.12);
const bad={challenges:[{id:'rollback1',name:'Should rollback'},{id:'rollback2',name:'Bad rank',private_rank:-1}]};
await assert.rejects(()=>db.query('select public.import_tracker($1::jsonb)',[JSON.stringify(bad)]));
assert.equal((await db.query("select * from public.challenges where name='Should rollback'")).rows.length,0);
await db.exec(`set request.jwt.claim.sub='${two}';`);
assert.equal((await db.query('select * from public.challenges')).rows.length,0);
assert.equal((await db.query('update public.challenges set public_score=99 where id=$1 returning id',[imported.id])).rows.length,0);
await assert.rejects(()=>db.query('insert into public.challenges(user_id,name) values($1,$2)',[one,'Denied']));
await db.exec(`set request.jwt.claim.sub='${one}';`);
await assert.rejects(()=>db.query('update public.challenges set user_id=$1 where id=$2',[two,imported.id]));
await db.query('delete from public.challenges where id=$1',[imported.id]);
await db.exec('reset role;set role anon;');
await assert.rejects(()=>db.query('select * from public.challenges'));
await assert.rejects(()=>db.query('select public.import_tracker($1::jsonb)',[JSON.stringify(payload)]));
console.log('PASS challenge schema conversion, old data preservation, removed submissions, CRUD, idempotent backup import, atomic rollback and RLS isolation');
await db.close();
