import { useState } from 'react';
import Modal from './Modal.jsx';
import { TYPES, METRICS, STATUSES, TYPE_COLORS, STATUS_COLORS, colorStyle, challengeValues, dateTimeInput, dateTimeTimestamp } from '../lib/domain.js';
export default function Editor({kind,item,onClose,onSave,onDelete}){
 const challenge=kind==='challenge';const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const [v,setV]=useState(()=>challenge?{created_date:dateTimeInput(item?.created_at||new Date()),name:item?.name||'',type:item?.type||'Classification',tags:(item?.tags||[]).join(', '),metric:item?.metric||'AUC',direction:item?.direction||'desc',baseline:item?.baseline??'',est_earn:item?.est_earn??'',actual_earn:item?.actual_earn??'',public_rank:item?.public_rank??'',private_rank:item?.private_rank??'',status_override:item?.status_override||''}:{version:item?.version||'',score:item?.score??'',status:item?.status||'Pending review'});
 const set=(key,value)=>setV(old=>({...old,[key]:value,...(key==='metric'?{direction:['RMSE','MAE'].includes(value)?'asc':'desc'}:{})}));
 const field=(key,label,type='text',extras={})=><label className="flex flex-col gap-2 text-xs text-slate-600" key={key}>{label}<input value={v[key]} onChange={e=>set(key,e.target.value)} type={type} {...extras}/></label>;
 const select=(key,label,values,colors)=><label className="flex flex-col gap-2 text-xs text-slate-600" key={key}>{label}<select value={v[key]} onChange={e=>set(key,e.target.value)} style={colors?colorStyle(colors[v[key]]):undefined}>{values.map(option=>{const [value,text]=Array.isArray(option)?option:[option,option];return <option key={value} value={value} style={colors?colorStyle(colors[value]):undefined}>{text}</option>})}</select></label>;
 async function save(e){e.preventDefault();setError('');setBusy(true);try{let values;if(challenge){values=challengeValues(v);values.created_at=item?.created_at&&v.created_date===dateTimeInput(item.created_at)?item.created_at:dateTimeTimestamp(v.created_date)}else{const version=v.version.trim(),score=Number(v.score);if(!version||v.score===''||!Number.isFinite(score)||!STATUSES.includes(v.status))throw new Error('Nhập version và điểm hợp lệ.');values={version,score,status:v.status}}await onSave(values);onClose()}catch(err){setError(err.message)}finally{setBusy(false)}}
 async function remove(){if(!window.confirm(challenge?'Xóa challenge và tất cả submission?':'Xóa submission này?'))return;setBusy(true);setError('');try{await onDelete();onClose()}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <Modal title={`${item?'Chỉnh sửa':'Thêm'} ${challenge?'challenge':'submission'}`} onClose={onClose} busy={busy}><form onSubmit={save}><fieldset disabled={busy} className="grid grid-cols-1 gap-4 sm:grid-cols-2">{challenge?<><div className="sm:col-span-2">{field('name','Challenge','text',{required:true,maxLength:160})}</div>{field('created_date','Ngày giờ challenge (giờ Việt Nam)','datetime-local',{required:true})}{select('type','Type',[...new Set([...TYPES,v.type])],TYPE_COLORS)}{field('tags','Tag (phân cách bằng dấu phẩy)')}{select('metric','Metric',METRICS)}{select('direction','Chiều điểm',[['desc','Điểm cao hơn tốt hơn'],['asc','Điểm thấp hơn tốt hơn']])}{field('baseline','Baseline','number',{step:'any'})}{field('est_earn','Est Earn (USD)','number',{min:0,step:'any'})}{field('actual_earn','Actual Earn (USD)','number',{min:0,step:'any'})}{field('public_rank','Vị trí của tôi · Public','number',{min:1,step:1})}{field('private_rank','Vị trí của tôi · Private','number',{min:1,step:1})}{select('status_override','Trạng thái challenge',[['','Tự động theo submission'],'Top leaderboard'],STATUS_COLORS)}<p className="text-xs leading-5 text-slate-500 sm:col-span-2">Pass khi có Pending review hoặc Approved. Fail khi tất cả submission đều Rejected. Top leaderboard khi chọn thủ công hoặc đạt hạng 1–3 Private.</p></>:<>{field('version','Latest version','text',{required:true,maxLength:160})}{field('score','Score','number',{required:true,step:'any'})}{select('status','Trạng thái',STATUSES,STATUS_COLORS)}</>}</fieldset>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex items-center justify-between gap-2">{item?<button disabled={busy} type="button" className="btn text-red-600" onClick={remove}>Xóa {challenge?'challenge':'submission'}</button>:<span/>}<div className="flex gap-2"><button type="button" className="btn" disabled={busy} onClick={onClose}>Hủy</button><button className="btn btn-primary" disabled={busy}>{busy?'Đang lưu…':'Lưu'}</button></div></div></form></Modal>
}
