import { useEffect, useRef, useState } from 'react';
import { Plus, Search, LogOut, Layers, RefreshCw, Database, Upload, Download } from 'lucide-react';
import { supabase, configured } from './lib/supabase.js';
import * as repo from './lib/repository.js';
import { challengeStatus, fmt, money, fmtDateTime, compareChallenges, paginateChallenges } from './lib/domain.js';
import Badge from './components/Badge.jsx';
import Editor from './components/Editor.jsx';
function Auth(){const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');async function submit(e){e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const credentials={email:f.get('email'),password:f.get('password')};const {data,error}=signup?await supabase.auth.signUp(credentials):await supabase.auth.signInWithPassword(credentials);if(error)throw error;if(signup&&!data.session)setMessage('Kiểm tra email để xác nhận tài khoản, sau đó đăng nhập.')}catch(err){setMessage(err.message)}finally{setBusy(false)}}return <div className="grid min-h-screen place-items-center p-6"><section className="card w-full max-w-md p-8"><Brand/><h1 className="mt-8 text-2xl font-bold">{signup?'Tạo tài khoản':'Chào mừng trở lại'}</h1><p className="mt-2 text-sm text-slate-500">Đăng nhập để đồng bộ challenge giữa thiết bị.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm">Email<input className="mt-2" name="email" type="email" autoComplete="username" required/></label><label className="block text-sm">Mật khẩu<input className="mt-2" name="password" type="password" minLength={signup?8:undefined} autoComplete={signup?'new-password':'current-password'} required/></label><button className="btn btn-primary w-full" disabled={busy}>{busy?'Đang xử lý…':signup?'Tạo tài khoản':'Đăng nhập'}</button></form>{message&&<p role="status" className="mt-4 text-sm text-slate-600">{message}</p>}<button disabled={busy} onClick={()=>{setSignup(!signup);setMessage('')}} className="mt-5 text-sm font-medium text-eris-600">{signup?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'}</button></section></div>}
function Brand(){return <div className="flex items-center gap-3 text-xl font-bold tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-xl bg-eris-600 text-2xl text-white">e</span><span>eris<span className="font-normal text-slate-400">tracker</span></span></div>}
function Setup(){return <main className="mx-auto max-w-xl p-8"><Brand/><section className="card mt-10 p-7"><Database className="text-eris-600"/><h1 className="mt-4 text-2xl font-bold">Kết nối Supabase</h1><p className="mt-3 text-sm leading-6 text-slate-600">Eris Tracker đã sẵn sàng. Cần cấu hình Supabase để đăng nhập và lưu dữ liệu.</p><ol className="mt-5 list-decimal space-y-3 pl-5 text-sm text-slate-600"><li>Chạy migration trong <code>supabase/migrations/</code>.</li><li>Điền URL và publishable key vào <code>.env.local</code> theo <code>.env.example</code>.</li><li>Khởi động lại ứng dụng.</li></ol><p className="mt-5 text-xs text-slate-400">Không sử dụng service_role key trong frontend.</p></section></main>}
export default function App(){const [session,setSession]=useState(null),[authLoading,setAuthLoading]=useState(configured),[authError,setAuthError]=useState('');useEffect(()=>{if(!supabase)return;let alive=true;const {data}=supabase.auth.onAuthStateChange((_event,current)=>{if(alive){setSession(current);setAuthLoading(false)}});supabase.auth.getSession().then(({data,error})=>{if(alive){if(error)setAuthError(error.message);else setSession(data.session);setAuthLoading(false)}});return ()=>{alive=false;data.subscription.unsubscribe()}},[]);if(!configured)return <Setup/>;if(authLoading)return <div className="p-10 text-slate-500">Đang kiểm tra tài khoản…</div>;if(authError)return <p role="alert" className="p-10 text-red-700">{authError}</p>;if(!session)return <Auth/>;return <Workspace key={session.user.id} user={session.user}/>}
function Workspace({user}){
 const [challenges,setChallenges]=useState([]),[query,setQuery]=useState(''),[sort,setSort]=useState({key:'created_at',direction:'desc'}),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[editor,setEditor]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[importing,setImporting]=useState(false),[notice,setNotice]=useState('');
 const request=useRef(0),fileRef=useRef(null);
 async function load(){const seq=++request.current;setLoading(true);setError('');try{const rows=await repo.loadChallenges();if(seq===request.current)setChallenges(rows)}catch(err){if(seq===request.current)setError(err.message)}finally{if(seq===request.current)setLoading(false)}}
 useEffect(()=>{load();return ()=>{request.current++}},[]);
 async function save(values){const row=await repo.saveChallenge(editor.item?.id,values,user.id);setChallenges(old=>editor.item?old.map(c=>c.id===row.id?row:c):[...old,row]);if(!editor.item)setPage(1)}
 async function remove(){await repo.deleteChallenge(editor.item.id);setChallenges(old=>old.filter(c=>c.id!==editor.item.id))}
 async function signOut(){const {error}=await supabase.auth.signOut();if(error)setError(error.message)}
 async function importFile(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{
  if(file.size>5*1024*1024)throw new Error('Tệp JSON tối đa 5 MB.');
  const payload=JSON.parse(await file.text());if(!Array.isArray(payload?.challenges))throw new Error('Tệp phải có danh sách challenges của Eris Tracker.');
  if(!window.confirm(`Nhập ${payload.challenges.length} challenge vào tài khoản này?`))return;
  setImporting(true);setError('');await repo.importTracker(payload);setPage(1);setNotice('Đã nhập challenge. Các bản ghi đã nhập không bị nhân đôi.');await load();
 }catch(err){setError(err.message)}finally{setImporting(false)}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({challenges},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='eris-tracker-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const visible=challenges.filter(c=>(c.name+' '+(c.tags||[]).join(' ')+' '+(c.difficulty||'')).toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>compareChallenges(a,b,sort.key,sort.direction));
 const pagination=paginateChallenges(visible,page,pageSize);
 const sortOptions=[['name','Tên'],['created_at','Ngày giờ'],['type','Type'],['difficulty','Difficulty'],['public_score','Public score'],['private_score','Private score'],['public_baseline','Public baseline'],['private_baseline','Private baseline'],['est_earn','Est Earn'],['actual_earn','Actual Earn'],['public_rank','Public Rank'],['private_rank','Private Rank']];
 return <div className="min-h-screen">
 <aside className="fixed inset-y-0 left-0 hidden w-60 flex-col border-r border-slate-200 bg-white p-6 lg:flex"><Brand/><div className="mt-10 rounded-lg border border-slate-100 bg-slate-50 p-4"><p className="text-[10px] tracking-widest text-slate-400">WORKSPACE</p><p className="mt-2 text-sm font-semibold">Machine Learning</p></div><div className="mt-6 flex items-center gap-3 rounded-lg bg-eris-50 p-3 text-sm font-semibold text-eris-600"><Layers size={17}/>Challenges</div><div className="mt-auto border-t border-slate-100 pt-5"><p className="truncate text-xs text-slate-500">{user.email}</p><button disabled={!!editor} onClick={signOut} className="mt-3 flex items-center gap-2 text-xs text-slate-500"><LogOut size={14}/>Đăng xuất</button></div></aside>
 <main className="px-4 pb-10 sm:px-8 lg:ml-60 lg:px-10">
 <header className="flex h-20 items-center justify-between gap-3 border-b border-slate-200 text-sm"><div className="text-slate-400">Workspace <span className="mx-3">/</span><span className="text-eris-800">Challenges</span></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs text-slate-500 sm:inline-flex">● &nbsp; Supabase</span><button disabled={loading||importing||!!editor} onClick={load} className="btn p-2" aria-label="Tải lại"><RefreshCw size={15}/></button><button className="btn p-2 lg:hidden" disabled={!!editor} aria-label="Đăng xuất" onClick={signOut}><LogOut size={15}/></button></div></header>
 {error&&<div role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice&&<p role="status" className="mt-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
 <div className="my-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-[11px] font-semibold tracking-[.18em] text-emerald-700">COMPETITION TRACKER</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Challenges</h1><p className="mt-2 text-sm text-slate-500">Theo dõi điểm Public / Private và kết quả của từng thử thách.</p></div><button className="btn btn-primary" disabled={loading||importing} onClick={()=>setEditor({item:null})}><Plus size={17}/>Thêm challenge</button></div>
 <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-400">{challenges.length} challenges</span>
 <label className="flex items-center gap-2 text-xs text-slate-500">Sắp xếp theo<select className="w-auto" value={sort.key} onChange={e=>{setSort(old=>({...old,key:e.target.value}));setPage(1)}}>{sortOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label className="flex items-center gap-2 text-xs text-slate-500">Thứ tự<select className="w-auto" value={sort.direction} onChange={e=>{setSort(old=>({...old,direction:e.target.value}));setPage(1)}}><option value="asc">Tăng dần ↑</option><option value="desc">Giảm dần ↓</option></select></label>
 <div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input aria-label="Tìm challenge, tag hoặc difficulty" className="pl-9" placeholder="Tìm challenge, tag, difficulty…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div></div>
 <section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1640px]"><thead><tr>{['STT','Challenge','Ngày giờ','Type','Difficulty','Tag','Public baseline','Private baseline','Public score','Private score','Est Earn','Actual Earn','Public Rank','Private Rank','Trạng thái'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>
 {!loading&&pagination.rows.map((c,i)=><tr key={c.id} className="hover:bg-eris-50/40"><td className="text-slate-400">{pagination.offset+i+1}</td><td><button className="text-left font-semibold text-eris-600" onClick={()=>setEditor({item:c})}>{c.name}</button></td><td className="whitespace-nowrap text-slate-500">{fmtDateTime(c.created_at)}</td><td><Badge value={c.type} type/></td><td><Tag>{c.difficulty||'—'}</Tag></td><td><div className="flex flex-wrap gap-1">{c.tags?.length?c.tags.map(t=><Tag key={t}>{t}</Tag>):'—'}</div></td><td className="mono">{fmt(c.public_baseline)}</td><td className="mono">{fmt(c.private_baseline)}</td><td className="mono text-emerald-700">{fmt(c.public_score)}</td><td className="mono text-emerald-700">{fmt(c.private_score)}</td><td>{money(c.est_earn)}</td><td>{money(c.actual_earn)}</td><td className="mono">{c.public_rank!=null?`#${c.public_rank}`:'—'}</td><td className="mono">{c.private_rank!=null?`#${c.private_rank}`:'—'}</td><td><Badge value={challengeStatus(c)}/></td></tr>)}
 {(loading||!visible.length)&&<Empty columns={15}>{loading?'Đang tải dữ liệu…':error?'Không tải được dữ liệu. Kiểm tra kết nối và thử tải lại.':'Chưa có challenge phù hợp. Thêm challenge để bắt đầu.'}</Empty>}
 </tbody></table></div>
 <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4"><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-500">Mỗi trang<select className="w-auto" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[10,20,50,100].map(size=><option key={size} value={size}>{size}</option>)}</select></label><span className="text-xs text-slate-400" role="status">{loading?'Đang tải…':`${pagination.start}–${pagination.end} / ${pagination.total} challenges`}</span></div><nav aria-label="Phân trang challenges" className="flex items-center gap-2"><button className="btn text-xs" disabled={loading||pagination.currentPage===1} onClick={()=>setPage(1)} aria-label="Trang đầu">«</button><button className="btn text-xs" disabled={loading||pagination.currentPage===1} onClick={()=>setPage(pagination.currentPage-1)}>Trước</button><span className="px-2 text-xs text-slate-500">Trang {pagination.currentPage} / {pagination.totalPages}</span><button className="btn text-xs" disabled={loading||pagination.currentPage===pagination.totalPages} onClick={()=>setPage(pagination.currentPage+1)}>Sau</button><button className="btn text-xs" disabled={loading||pagination.currentPage===pagination.totalPages} onClick={()=>setPage(pagination.totalPages)} aria-label="Trang cuối">»</button></nav></div>
 <p className="border-t border-slate-100 px-5 py-3 text-xs text-slate-400">Nhấp vào tên challenge để chỉnh sửa thông tin.</p></section>
 <div className="mt-5 flex flex-wrap gap-2"><button className="btn text-xs" onClick={exportData} disabled={loading||!!error}><Download size={14}/>Xuất JSON</button><button className="btn text-xs" onClick={()=>fileRef.current.click()} disabled={loading||importing}><Upload size={14}/>Nhập tệp JSON</button><input ref={fileRef} type="file" accept=".json,application/json" className="hidden" onChange={importFile}/></div>
 </main>{editor&&<Editor key={editor.item?.id||'new'} item={editor.item} onClose={()=>setEditor(null)} onSave={save} onDelete={remove}/>}</div>
}
function Tag({children}){return <span className="rounded bg-slate-100 px-2 py-1 text-[11px] text-slate-500">{children}</span>}
function Empty({columns,children}){return <tr><td colSpan={columns} className="py-14 text-center text-sm text-slate-400">{children}</td></tr>}
